apiVersion: v2
name: infra-platform
description: A Helm chart for Infra Platform domain (gitea, zitadel, observability, caddy)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: gitea
    version: 0.1.0
    repository: "file://./charts/gitea"
  - name: zitadel
    version: 0.1.0
    repository: "file://./charts/zitadel"
  - name: observability
    version: 0.1.0
    repository: "file://./charts/observability"
  - name: caddy
    version: 0.1.0
    repository: "file://./charts/caddy"
